# SPDX-FileCopyrightText: Simon Schneegans <code@simonschneegans.de>
# SPDX-License-Identifier: CC0-1.0

name: Build Badges

on: [push]

jobs:
  answer-badge:
    name: Create Answer Badge
    runs-on: ubuntu-latest
    steps:
      - name: Get the Numbers
        run: echo "ANSWER=42" >> $GITHUB_ENV
      - name: Create the Badge
        uses: https://hub.cybercinch.nz/cybercinch/dynamic-badges-action@master
        with:
          auth: ${{ secrets.BADGE_API_TOKEN }}
          host: https://badges.cybercinch.nz/cybercinch/dynamic-badges-action/answer
          label: The Answer
          message: is ${{ env.ANSWER }}
          valColorRange: ${{ env.ANSWER }}
          maxColorRange: 100
          minColorRange: 0

  color-range-badges:
    name: "Create Color Range Badges"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        total:
          - 0
          - 10
          - 20
          - 30
          - 40
          - 50
          - 60
          - 70
          - 80
          - 90
          - 100
    steps:
      - name: "Make badge"
        uses: https://hub.cybercinch.nz/cybercinch/dynamic-badges-action@master
        with:
          auth: ${{ secrets.BADGE_API_TOKEN }}
          host: https://badges.cybercinch.nz/cybercinch/dynamic-badges-action/color_badge_${{ matrix.total }}
          label: Coverage
          message: ${{ matrix.total }}%
          minColorRange: 50
          maxColorRange: 90
          valColorRange: ${{ matrix.total }}
